In [12]:
import numpy as np

# The basics

In [13]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [14]:
b = np.array([[9.0 , 8.0 , 7.0],[4.0 , 5.0 ,6.0]])
print(b)

[[9. 8. 7.]
 [4. 5. 6.]]


In [15]:
#Get Dimension
b.ndim

2

In [16]:
#Get shape
b.shape

(2, 3)

In [17]:
#Get type
a.dtype

dtype('int32')

In [18]:
#Get size
b.size

6

In [19]:
#Get total size
a.nbytes

12

# Accessing/Changing specific elements , rows , columns.

In [20]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [21]:
#Get a specific element [r,c]
a[1,5]

13

In [22]:
#Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [23]:
#Get a specific column
a[:, 2]

array([ 3, 10])

In [24]:
#Getting a little more fancy [startindex:endindex:stepsize]
a[0,1:-1:2]

array([2, 4, 6])

In [25]:
a[1,5] = 20
print(a)

a[:,2] = [1,2]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


*3-d example

In [26]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [27]:
#Get specific element (work outside in)
b[0,1,1]

4

In [28]:
#replace
b[:,1,:] = [[9,9],[8,8]]

In [29]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

# Initializing Different Types of Arrays

In [30]:
#All 0s matrix
np.zeros((2,3), dtype = 'int32')

array([[0, 0, 0],
       [0, 0, 0]])

In [31]:
#All 1s matrix
np.ones((2,3), dtype='int32')

array([[1, 1, 1],
       [1, 1, 1]])

In [32]:
#Any anther number
np.full((2,2),85)

array([[85, 85],
       [85, 85]])

In [36]:
#Any anther number (full_like)
np.full_like(a.shape , 4)

array([4, 4])

In [38]:
#random decimal number
np.random.rand(4,2)

array([[0.82818066, 0.63709261],
       [0.09199716, 0.68905859],
       [0.14109766, 0.37307418],
       [0.59545217, 0.38404416]])

In [42]:
#random intger number 
np.random.randint(3,7,size=(3,4))

array([[4, 5, 5, 6],
       [4, 3, 5, 4],
       [3, 5, 6, 6]])

In [44]:
#the identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [48]:
# repeat any array
arr = np.array([[1 , 2 , 3]])
r1 = np.repeat(arr , 3 , axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [55]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:4 , 1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### Be careful when copying array!!!

In [61]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)
print(b)

[1 2 3]
[100   2   3]


## Mathematics

In [62]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [63]:
a + 2

array([3, 4, 5, 6])

In [64]:
a - 2

array([-1,  0,  1,  2])

In [65]:
a * 2

array([2, 4, 6, 8])

In [66]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [67]:
b = np. array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [68]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [98]:
# take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [99]:
a.std()

2.581988897471611

In [100]:
a.mean()

5.0

In [101]:
np.linspace(1,10,100)

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

### Linear Algebra

In [71]:
a = np.ones((2,3))
print(a)

b = np.full((3,2) , 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [72]:
#find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

### Statistics

In [73]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [74]:
np.min(stats)

1

In [77]:
np.max(stats , axis=1)

array([3, 6])

In [78]:
np.sum(stats , axis=0)

array([5, 7, 9])

### Reorganizing Arrays

In [82]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [83]:
#Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [84]:
#Horizonatal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous

#### Load Data from File

In [92]:
filedata = np.genfromtxt('data.txt' , delimiter=',')
filedata = filedata.astype('int32')
filedata

array([[  1,   2,  35,  57, 123,  45,  78,   9,  23,  43],
       [ 54,  44,  32,  12,  13,  34,  76,  99,  98,  72],
       [  4,   5,   3,  58,   2,   6,  65,  76,  98,  77],
       [ 87,  54,  43,  32,  31,  41,  43,  33,  45,  23]])

#### Boolean Masking and Advanced Indexing

In [94]:
filedata[filedata > 50]

array([ 57, 123,  78,  54,  76,  99,  98,  72,  58,  65,  76,  98,  77,
        87,  54])

In [96]:
#You can index with a list in NumPy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [97]:
((filedata > 50) & (filedata < 100))

array([[False, False, False,  True, False, False,  True, False, False,
        False],
       [ True, False, False, False, False, False,  True,  True,  True,
         True],
       [False, False, False,  True, False, False,  True,  True,  True,
         True],
       [ True,  True, False, False, False, False, False, False, False,
        False]])